Repository DataCater/datacater, pull requests merged in 2022-10, with the labels that each got.

#6 fix(housekeeping): proper naming of project and adding 3rd party licenses
  licenses/platform-api/third_party.md
  licenses/python-runner/third_party.md
  licenses/serde/third_party.md
  licenses/ui/third_party.md
  settings.gradle
Labels: documentation

#5 fix(chart): remove SC from template
  helm-charts/datacater/templates/postgres.yaml
  helm-charts/datacater/templates/statefulset.yaml
  k8s-manifests/minikube-with-postgres-ns-default.yaml
Labels: bug, enhancement

#7 chore(docs): Documentation API authorization
  platform-api/src/main/java/io/datacater/core/DataCater.java
  platform-api/src/main/java/io/datacater/core/authentication/AuthenticationEndpoint.java
  platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
  platform-api/src/main/java/io/datacater/core/filter/FilterEndpoint.java
  platform-api/src/main/java/io/datacater/core/pipeline/PipelineEndpoint.java
  platform-api/src/main/java/io/datacater/core/stream/StreamEndpoint.java
  platform-api/src/main/java/io/datacater/core/transform/TransformEndpoint.java
Labels: documentation

#8 feat(ui): Warn about data type mismatches
  ui/src/components/pipelines/PipelineDesigner.js
  ui/src/components/pipelines/pipeline_designer/Grid.js
  ui/src/components/pipelines/pipeline_designer/context_bar/filter/Attribute.js
  ui/src/components/pipelines/pipeline_designer/context_bar/filter/AttributeFilterList.js
  ui/src/components/pipelines/pipeline_designer/context_bar/filter/Edit.js
  ui/src/components/pipelines/pipeline_designer/context_bar/transformation/Attribute.js
  ui/src/components/pipelines/pipeline_designer/context_bar/transformation/AttributeTransformationList.js
  ui/src/components/pipelines/pipeline_designer/context_bar/transformation/Config.js
  ui/src/components/pipelines/pipeline_designer/context_bar/transformation/Edit.js
  ui/src/components/pipelines/pipeline_designer/grid/DataTypeIcon.js
  ui/src/components/pipelines/pipeline_designer/grid/TableHeaderCell.js
  ui/src/scss/context-bar.scss
Labels: ui

#17 feat(python): Update Python to 3.11
  python-runner/Dockerfile
  python-runner/build.sh
Labels: python-runner
